services:
  - type: web
    name: product-importer
    env: docker
    dockerfilePath: Dockerfile
    dockerContext: .
    healthCheckPath: /
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: product-importer-db
          property: connectionString
      - key: RENDER_DATABASE_URL
        fromDatabase:
          name: product-importer-db
          property: connectionString
      - key: REDIS_URL
        fromService:
          name: product-importer-redis
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"

  - type: worker
    name: product-importer-worker
    env: docker
    dockerfilePath: Dockerfile.worker
    dockerContext: .
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: product-importer-db
          property: connectionString
      - key: RENDER_DATABASE_URL
        fromDatabase:
          name: product-importer-db
          property: connectionString
      - key: REDIS_URL
        fromService:
          name: product-importer-redis
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"

databases:
  - name: product-importer-db
    databaseName: product_importer_db

redis:
  - name: product-importer-redis